### ISSUE TITLE
Documentation: only python >=3.9 is supported?

### ISSUE THREAD

**Issue by pfliu-nlp** [neulab/explainaboard_client#28]
It seems that the client only supports python >=3.9, if yes,
* (1) we need to clarify this and,
* (2) we'd better document how to install python 3.9 WITH and WITHOUT `sudo` as well.

**Comment by neubig** [comment]
@pfliu-nlp : tests seem to be passing on version 3.8: https://github.com/neulab/explainaboard_client/actions/runs/3275693415/jobs/5390853373

Do you have a way to reproduce the error you were experiencing?

**Comment by neubig** [comment]
Closing, please re-open if it can be reproduced.
