### ISSUE TITLE
Breaking changes to resolve before upgrading to 0.0.21

### ISSUE THREAD

**Issue by OscarWang114** [neulab/explainaboard_client#58]
The changes in PR https://github.com/neulab/explainaboard_web/pull/526 will break the following code: https://github.com/neulab/explainaboard_client/blob/e4ec42991d22327b69952891a8b5750fe27d6c4c/explainaboard_client/cli/evaluate_system.py#L159

We should resolve this when upgrading to API client 0.0.21

**Comment by lyuyangh** [comment]
Thanks for the discussion! I tested `explainaboard_client` and I don't think this PR would affect that project. I only changed `SystemInfo` (the object we cache) in this PR which is only used in `POST /systems/analyses`. The client uses `GET /systems` and `POST /systems` instead so it should still work.

**Comment by OscarWang114** [comment]
Closing as it's not relevant anymore.
